### ISSUE TITLE
Failed to decode invoice error from wos

### ISSUE THREAD

**Issue by anybeegirl** [massmux/SatsMobiBot#15]
When sending to @ address or anon LNURL from WoS, "error failed to decode invoice" appears. Sending to lnbc... invoice with an amount works fine.

**Comment by massmux** [comment]
please be more descriptive. better with an example, so that we can try to replicate the iussue

**Comment by massmux** [comment]
finally we noticed that this is caused because of firewall filtering US IP addresses. This firewall is in place to avoid US users, who are forbidden using the service.
